### ISSUE TITLE
[18614, 21856] Improve screenshot UX

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/UserVoice#319]
- [ ] [Allow screens to be selected separately, instead of all screens being included in the same screenshot](https://github.com/DeskDirector/UserVoice/issues/442)

- [ ] [Allow user to view screenshots before they are submitted to the ticket](https://github.com/DeskDirector/UserVoice/issues/443)

- [ ] [Unique name for screenshots so that when they are downloaded, they do not try to override each other on the file system](https://github.com/DeskDirector/UserVoice/issues/444)

- [ ] [Clear indication of screenshot been taken, or about to be taken](https://github.com/DeskDirector/UserVoice/issues/445)

**Comment by Lowell-Syncrety** [comment]
Could you add back the capability to take the screenshot while in an existing ticket, not just have it only in the new ticket section? Probably not a lot of people use this but I just noticed it's no longer available after creating a ticket.

**Comment by Andrew-Lahikainen** [comment]
@Lowell-Syncrety this should be available as far as I'm aware - could you log a support ticket for that?

**Comment by Lowell-Syncrety** [comment]
Yeah, just checked again and either from the desktop app or the web portal, no screenshot button in an existing open ticket. I'll put in a ticket.

**Comment by justinDJC** [comment]
+1 on this!

In UAT pre-rollout, every user assumed the program had crashed or they did something wrong.

Need a countdown for the screenshot at minimum. Some 'snipping tool' like features would be fantastic. Dragging the window to select the screenshot area. and some mangement of the screenshot afterwards. even if just clicking the filename to have it open the screenshot.

**Comment by Andrew-Lahikainen** [comment]
@justinDJC we've added a dialog with a countdown before a screenshot is taken. There is also a preview of the screenshot where the user can view it before attaching to the ticket.
